//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lyrics.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class lyricsTable
    {
        public int lyric_ID { get; set; }
        public string lyric_title { get; set; }
        public string artist { get; set; }
        public string Additional_vocals { get; set; }
        public string composed_by { get; set; }
        public string produced_by { get; set; }
        public string lyrics_by { get; set; }
        public string singers { get; set; }
        public string main_lyrics { get; set; }
        public string information { get; set; }
        public string audio_link { get; set; }
        public string video_link { get; set; }
        public Nullable<int> category_id { get; set; }
        public string image { get; set; }
        public Nullable<int> sub_category_id { get; set; }
    
        public virtual LyricsCategoryTable LyricsCategoryTable { get; set; }
        public virtual LyricsSubCategoryTable LyricsSubCategoryTable { get; set; }
    }
}
