//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lyrics.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LyricsSubCategoryTable
    {
        public LyricsSubCategoryTable()
        {
            this.lyricsTable = new HashSet<lyricsTable>();
        }
    
        public int sub_category_id { get; set; }
        public string sub_category_name { get; set; }
        public Nullable<int> category_id { get; set; }
    
        public virtual LyricsCategoryTable LyricsCategoryTable { get; set; }
        public virtual ICollection<lyricsTable> lyricsTable { get; set; }
    }
}
